### ISSUE TITLE
Add `useMedia` function

### ISSUE THREAD

**Issue by logaretm** [logaretm/vue-use-web#13]
We already have `usePreferredColorScheme` scheme that uses media queries API.

Having a raw `useMediaQuery` function would be really cool for components that need MQ info, we could also refactor `usePreferredColorScheme` to use this function instead.

```js
const matches = useMedia('(max-width: 600px)');
```

This should allow users to watch arbitrary media queries, for example:

```js
const isPhone = useMedia('(max-width: 480px)');
const isTablet = useMedia('(max-width: 1080)');
const isDesktop = useMedia('(max-width: 2160)');
```

> Hint: take a look at `usePreferredColorScheme` implementation, and `window.matchMedia`.

**Comment by eaglejs** [comment]
I think this needs a little more information. I see that you have a code snippet here, but I'm trying to understand what is the use case here?

For example:

"As a user, I want to be able to adjust my browser window, so that the colors and themes of the application will adjust accordingly."

Acceptance Criteria:

- It should take phone (480px), tablet (1080px), and desktop (2160px) widths into account.
- It should be configurable.
- It should ... you get the point. :) 

As of right now, and I think most people do not understand what is needed and that's probably the reason no one has touched this issue even for being a "good first issue". I want to take this on. but I am not sure what problem you are trying to solve. :)

**Comment by logaretm** [comment]
@eaglejs Thanks, I added a small example for what is the use-case for it, hopefully it is clearer now.

There are no specific "widths" to take into account, this is a function to do arbitrary media queries via `window.matchMedia`.
